### ISSUE TITLE
Dynamic CSS file doesn’t work with WordPress custom content directory

### ISSUE THREAD

**Issue by LeBenLeBen** [minimus/wp-special-textboxes#1]
Let’s say I have the following tree architecture for my WordPress setup:

```
.
├── content/
├── index.php
├── wp-config.php
└── wordpress/
```

As you can see I have both WordPress and the content folder in custom directories. This is a problem with WP Special Textboxes in `wp-special-textboxes.css.php`, at the beginning of the file, where it tries to determine WordPress root path:

```
$root = dirname(dirname(dirname(dirname(dirname(__FILE__)))));
...
require_once( $root . '/wp-load.php' );
```

It obviously doesn’t find anything there in my case. Sadly there’s no easy solution for this because we don’t know where `wp-load.php` lives at this point. 

Therefor it would be great to review this part a bit so it can work wherever your WordPress/content/plugins directories are. It’s actually a bad practice to manually load `wp-load.php` like this for security and performance reasons. You can find additional information there:

- http://ottodestruct.com/blog/2010/dont-include-wp-load-please/
- https://willnorris.com/2009/06/wordpress-plugin-pet-peeve-2-direct-calls-to-plugin-files

**Comment by minimus** [comment]
Resolved...
